New ci-setup command
jfrog/jfrog-cli pull request #1027
Opened 2021-03-25 17:19 UTC by talarian1

- [ ] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-03-29 14:44 UTC, eyalbe4 requested changes
I suggest we add the following text before the first command prompt. Let's color the two titles.

**About this command**
This command sets up a basic CI pipeline which uses the JFrog Platform.
It currently supports maven, gradle and npm, but additional package managers will be added in the future.
The generated CI pipeline is based on JFrog Pipelines, but additional CI providers will be added in the future.

**Important**
1. When asked to provide credentials for your JFrog Platform and Git provider, please make sure the credentials have admin privileges.
2. You can exit the command by hitting 'control + C' at any time. The values you provided before exiting are saved (with the exception of passwords and tokens) and will be set as defaults the next tine you run the command.

2021-03-29 14:45 UTC, eyalbe4 requested changes
1. If yuo provide a branch that does not exist, no error message is prompted.
2. [Error] ./jfrog-vcs-workspace isn't empty. --> [Error] The ./jfrog-vcs-workspace directory isn't empty.

2021-03-30 21:05 UTC, eyalbe4 commented on general/cisetup/pipelinesyaml.go
> +
I suggest we orginize the code in this file inside a struct named JFrogPipelinesYamlGenerator. This struct can have one public entry point named Generate.

Let's do the same for the code inside ```pipelinesrun```. We can perhaps name the struct there ```JFrogPipelinesConfigurator```.

Both structs should move to jfrog-cli-core IMO.

2021-03-30 21:10 UTC, eyalbe4 commented on general/cisetup/utils.go
> +func GetVirtualRepo(serviceDetails *utilsconfig.ServerDetails, repoKey string) (*services.VirtualRepositoryBaseParams, error) {
Missing new-line before function.

2021-03-30 21:14 UTC, eyalbe4 commented on utils/cliutils/commandsflags.go
> +		Name:  Replace,
Flag should have [Default: false] and not [Optional].

2021-03-30 21:14 UTC, eyalbe4 commented on utils/cliutils/commandsflags.go
> +		Usage: "[Optional] Set to true if you'd like to create an admin user.` `",
Flag should have [Default: false] and not [Optional].

2021-03-31 08:14 UTC, RobiNino commented on general/cisetup/cisetup.go
> +	ideUserName              = "ide-user"
I think we better come up with a name that is a bit more unique so the chances of such user existing prior to the setup are low

2021-03-31 15:45 UTC, eyalbe4 commented on general/cisetup/cisetup.go
> +	ideUserName              = "ide-user"
OK - let's change it to "ide-developer" then.

2021-03-31 16:02 UTC, merged