Adding "go get" test
jfrog/jfrog-cli pull request #1092
Opened 2021-05-27 20:18 UTC by gailazar300

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-05-27 23:47 UTC, eyalbe4 requested changes

2021-05-27 23:47 UTC, eyalbe4 commented on utils/tests/artifactoryconsts.go
>  	GoRepo           = "cli-tests-go"
GoRepo --> GoLocalRepo
cli-tests-go --> cli-tests-go-local

2021-05-27 23:47 UTC, eyalbe4 commented on utils/tests/utils.go
>  		"${GO_REPO}":                   GoRepo,
"${GO_REPO}"  --> "${GO_LOCAL_REPO}" 
GoRepo --> GoLocalRepo

2021-07-25 12:45 UTC, asafgabai commented
The test will be merged in this PR:
#1161

2021-07-25 12:45 UTC, closed without merging