Adding tests to 'xr curl' command
jfrog/jfrog-cli pull request #1354
Opened 2021-12-21 11:09 UTC by gailazar300

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-12-21 11:33 UTC, yahavi requested changes
Looks good! 😎 
Please also add `CleanXrayTests` in main_test.go at`tearDownIntegrationTests()`.
This cleanup method should do the same as `cleanBuildToolsTest()`:
```go
os.Unsetenv(coreutils.HomeDir)
tests.CleanFileSystem()
```
 Maybe we can rename `cleanBuildToolsTest()` to something more generic and use it.

2021-12-21 11:33 UTC, yahavi commented on xray_test.go
> +	assert.Error(t, err)
```suggestion
	assert.EqualError(t, err, "Server ID 'not_configured_name' does not exist.")
```

2021-12-21 11:33 UTC, yahavi commented on xray_test.go
> +	initXrayTest(t, commands.GraphScanMinXrayVersion)
I'm not sure we need the version check, can we just check this?
```go
if !*tests.TestXray {
	t.Skip("Skipping Xray test. To run Xray test add the '-test.xray=true' option.")
}
```
For example, maybe in `initXrayVersion` we can return early when no min Xray version is provided as a parameter.

2021-12-27 09:45 UTC, eyalbe4 requested changes

2021-12-27 09:45 UTC, eyalbe4 commented on main_test.go
> +	if *tests.TestNpm || *tests.TestGradle || *tests.TestMaven || *tests.TestGo || *tests.TestNuget || *tests.TestPip || *tests.TestDocker || *tests.TestXray {
I'm not sure this if statement is actually needed.

2022-06-07 14:16 UTC, merged