Run tests on local Artifactory
jfrog/jfrog-cli pull request #1375
Opened 2022-01-12 08:06 UTC by RobiNino

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2022-01-16 14:35 UTC, yahavi requested changes

2022-01-16 14:35 UTC, yahavi commented on .github/workflows/tests.yml
> +          go install github.com/RobiNino/jfrog-testing-infra/local-rt-setup@latest
I think the latest is the default
```suggestion
          go install github.com/RobiNino/jfrog-testing-infra/local-rt-setup
```

2022-01-16 14:35 UTC, yahavi commented on .github/workflows/tests.yml
> +        run: go test -v github.com/jfrog/jfrog-cli --timeout 0 --test.${{ matrix.suite }}=true --jfrog.url='http://localhost:8081/' --jfrog.user='admin' --jfrog.password='password' --ci.runId=${{ run
Remove default values
```suggestion
        run: go test -v github.com/jfrog/jfrog-cli --timeout 0 --test.${{ matrix.suite }}=true --ci.runId=${{ runner.os }}-${{ matrix.suite }}
```

2022-01-16 14:35 UTC, yahavi commented on utils/tests/utils.go
> +	DockerPromoteLocalRepo = flag.String("rt.dockerPromoteLocalRepo", "", "Docker promote local repo")
Please document `rt.dockerPromoteLocalRepo` in the README
https://github.com/RobiNino/jfrog-cli/tree/tests-local-rt#docker-tests

2022-01-16 15:03 UTC, RobiNino commented on .github/workflows/tests.yml
> +          go install github.com/RobiNino/jfrog-testing-infra/local-rt-setup@latest
Tag is required:
```
$ go install github.com/RobiNino/jfrog-testing-infra/go
no required module provides package github.com/RobiNino/jfrog-testing-infra/go; to add it:
	go get github.com/RobiNino/jfrog-testing-infra/go

2022-01-16 15:18 UTC, yahavi requested changes

2022-01-16 15:18 UTC, yahavi commented on README.md
> +| `-rt.DockerLocalRepo`        | Artifactory Docker local repository name.                      |
```suggestion
| `-rt.dockerLocalRepo`        | Artifactory Docker local repository name.                      |
```

2022-01-17 06:50 UTC, eyalbe4 requested changes

2022-01-17 06:50 UTC, eyalbe4 commented on .github/workflows/tests.yml
> +      - name: Setup Artifactory # TODO change to jfrog
I think this TODO comment isn't needed.

2022-01-17 08:05 UTC, RobiNino commented on .github/workflows/tests.yml
> +      - name: Setup Artifactory # TODO change to jfrog
It is for me, to stop using my fork

2022-01-17 10:33 UTC, merged