Automatically unlabel 'safe to test' after tests run
jfrog/jfrog-cli pull request #1497
Opened 2022-04-04 14:28 UTC by talarian1

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2022-04-05 06:34 UTC, yahavi requested changes
Let's also rename Go-Lint to something else. I suggest `Pretest`

2022-04-05 06:34 UTC, yahavi commented on .github/workflows/tests.yml
>        fail-fast: false
This not needed if you're using only 1 agent
```suggestion
```

2022-04-05 06:34 UTC, yahavi commented on .github/workflows/tests.yml
> +    needs: Go-Lint
This job can safely run without any restrictions
```suggestion
```

2022-04-09 11:11 UTC, eyalbe4 requested changes
I noticed the following files were removed.
I assume this is because they are unused. Just making sure.
<img width="397" alt="image" src="https://user-images.githubusercontent.com/7830056/162569348-4f4aadf9-57ea-4ddf-a98f-a82fc9de704c.png">

2022-04-10 08:17 UTC, talarian1 commented
@eyalbe4, worse than that. 
Those files, cause the flowing messages to appear :

> 08:28:49 [Warn] The file /Users/yahavi/.nuget/packages/system.reflection.metadata/1.6.0/system.reflection.metadata.1.6.0.nupkg doesn't exist in the NuGet cache directory but it does exist as a target in the assets files. Skipping adding this dependency to the build info. This might be because the package already exists in a different NuGet cache, possibly the SDK's NuGetFallbackFolder cache. Removing the package from this cache may resolve the issue. 

And fails the `TestXrayAuditNugetMultiProject`

2022-08-18 11:52 UTC, merged