Added Intro Command
jfrog/jfrog-cli pull request #1580
Opened 2022-06-23 12:34 UTC by omerzi

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----
The Intro command is a new command that guides the users through the environment setup and configuration right after CLI installation.

2022-07-09 21:08 UTC, eyalbe4 requested changes
If we haven't already, I suggest we test the npm installation locally on both ma, Linux and Windows.
Let's also test the rpm and debian installation locally if we haven't already.

2022-07-10 12:40 UTC, omerzi commented on build/npm/v2/init.js
> +    spawn("jf", ['intro'], {stdio: 'inherit', shell: true});
I found that there is a function "getFileName" that returns the relevant cli ('jfrog'/'jf'), so I switched to that and it works locally. 
Regarding the duplication - I noticed that almost every function is duplicated between v2-jf/init.js and v2/init.js. Is there a reason for this? Would it be better to open a new 'utils.js' file with each duplicated function and call them from each init.js?

2022-07-10 13:00 UTC, omerzi commented on build/setupcli/jf.sh
> +            echo -e "\e[1;32m Thank you for installing JFrog CLI! 🐸\033[0mֿ"
Done

2022-07-10 13:35 UTC, omerzi commented on main.go
> +	if !serverExists || err != nil {
Done

2022-07-10 14:22 UTC, eyalbe4 commented on build/npm/v2/init.js
> +    spawn("jf", ['intro'], {stdio: 'inherit', shell: true});
I think we should remove all duplications @omerzi. Having duplicate code makes it harder to maintain the code. Please go ahead and remove older duplications as well.

2022-07-11 09:53 UTC, omerzi commented on build/npm/v2/init.js
> +    spawn("jf", ['intro'], {stdio: 'inherit', shell: true});
Hey Eyal, 
I tested this and tried to understand how it should be done. There are two separate NPM packages (v2, v2-jf), and I want them to share logic from a third file. There's a problem where they won't recognize the 3rd file unless I make him into a separate npm package and then rely on it as a dependency. However, it seems a bit overkill? We could also copy it when building, but then we won't be able to debug it or see the inner implementations of some functions (the init.js files will call functions that are unknown to them until we build them). Right now as I see it,  the third option is to keep the state as it is with the code duplication, which I guess maybe it is not that bad as this file is not often updated. What do you think will be the proper way to handle this case?

2022-07-25 14:43 UTC, merged