Transfer files - Add status flag
jfrog/jfrog-cli pull request #1722
Opened 2022-10-14 11:15 UTC by yahavi

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

Depends on https://github.com/jfrog/jfrog-cli-core/pull/581

2022-10-16 06:07 UTC, eyalbe4 requested changes

2022-10-16 06:07 UTC, eyalbe4 commented on utils/cliutils/commandsflags.go
> +		Usage: "[Default: false] Set to true to show the status of a running transfer-files command.` `",
"[Default: false] Set to true to show the status of a running transfer-files command.` `",
-->
"[Default: false] Set to true to show the status of the transfer-files command currently in progress.` `",

2022-10-16 06:07 UTC, eyalbe4 commented on utils/cliutils/commandsflags.go
> +	Status           = "status"
Status --> status

2022-10-18 11:05 UTC, yahavi commented on utils/cliutils/commandsflags.go
> +	Status           = "status"
I'm using this variable in cli.go

2022-10-18 11:35 UTC, merged