set sortBy property as type array of strings
jfrog/jfrog-cli pull request #1831
Opened 2023-02-14 10:22 UTC by felicepagano

Hello

using a filespec defined as follow

`{
    "files": [
        {
            "sortBy": "path",
            "sortOrder": "asc",
            "aql": {
                "items.find": {
                    "repo": {
                        "$match": "docker-*"
                    },
                    "type": "folder",
                    "$and": [
                        {"@name": {"$match":"*"}},
                        {"@version": {"$match":"*"}}
                    ]
                }
            }
        }
    ]
}`

and calling the cli with the previous spec file content 

`jf rt s --spec=search-docker.filespec`

I receive the following error

`
[Debug] JFrog CLI version: 2.34.1
[Debug] OS/Arch: darwin/amd64
[🚨Error] json: cannot unmarshal string into Go struct field File.Files.SortBy of type []string
`

This should means that in the filespec-schema.json the sortBy property should be defined as type array of strings.

2023-02-14 10:36 UTC, felicepagano commented
I have read the CLA Document and I hereby sign the CLA

2023-02-14 14:19 UTC, yahavi requested changes
@felicepagano thanks a lot for this contribution!
Please see my minor comment to fix the description as well.

2023-02-14 14:19 UTC, yahavi commented on schema/filespec-schema.json
>          "description": "A list of semicolon-separated fields to sort by. The fields must be part of the 'items' AQL domain.",
Let's fix also the description
```suggestion
        "description": "A list of fields to sort by. The fields must be part of the 'items' AQL domain.",
```

2023-02-15 06:59 UTC, merged

2023-02-15 07:06 UTC, yahavi commented
Thanks again for your time and contribution, @felicepagano!
We merged this PR to the dev branch. This change will be effective globally in the SchemaStore in the next JFrog CLI release.