Curation
jfrog/jfrog-cli pull request #1909
Opened 2023-04-20 22:39 UTC by asafambar

- [ ] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2023-04-23 07:49 UTC, asafambar commented
I have read the CLA Document and I hereby sign the CLA

2023-05-04 11:52 UTC, eyalbe4 requested changes
Is `sarif` supported as an output format? If not, let's set the correct option description for this command.
![image](https://user-images.githubusercontent.com/7830056/236195461-db3e2290-4da1-45d5-a7cd-e3b2ea7abd37.png)

Let's document the new command in the `CLI-for-JFrog-Xray.md` file.

2023-05-04 11:52 UTC, eyalbe4 commented on scan/cli.go
> +const curationAuditCategory = "Curation Audit"
Let's remove this const and use `auditScanCategory` for the `curation-audit` command category.

2023-05-04 11:52 UTC, eyalbe4 commented on scan/cli.go
> +			Aliases:      []string{"caud"},
caud --> ca

2023-05-04 11:52 UTC, eyalbe4 commented on scan/cli.go
> +func CurationCommand(c *cli.Context) error {
CurationCommand --> CurationAuditCmd

2023-05-04 11:52 UTC, eyalbe4 commented on scan/cli.go
> +	auditCmd.GraphBasicParams = &xrCmdUtils.GraphBasicParams{}
It's better to initialize this struct inside the `NewGenericAuditCommand()` function.

2023-05-04 11:52 UTC, eyalbe4 commented on scan/cli.go
> +func createCurtainCmd(c *cli.Context) (*curation.Command, error) {
This function seems redundant. Let's move its content into the `CurationAuditCmd` function.

2023-05-04 11:52 UTC, eyalbe4 commented on scan/cli.go
> +func CurationCommand(c *cli.Context) error {
CurationCommand  --> CurationAuditCmd

2023-05-04 11:52 UTC, eyalbe4 commented on utils/cliutils/commandsflags.go
> +	Curation      = "curation-audit"
Curation --> CurationAudit

2023-05-04 11:52 UTC, eyalbe4 commented on utils/cliutils/commandsflags.go
> +		xrOutput, DepType, workingDirs,
The `DepType` is currently redundant and should be removed.

2023-05-16 17:08 UTC, eyalbe4 requested changes

2023-05-16 17:08 UTC, eyalbe4 commented on scan/cli.go
> +func CurationCmd(c *cli.Context) error {
Missing new-line before function.

2023-05-16 17:08 UTC, eyalbe4 commented on xray_test.go
> +	defer os.Chdir(rootDir)
Should be replaced with - 
```
	defer func() {
		assert.NoError(t, os.Chdir(rootDir))
	}()
```

2023-05-16 23:03 UTC, merged