Add categories to JFrog Artifactory commands
jfrog/jfrog-cli pull request #2544
Opened 2024-05-09 16:50 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/jfrog-cli/CONTRIBUTING.md#tests) have passed. If this feature is not already covered by the tests, new tests have been added.
- [ ] The pull request is targeting the `dev` branch.
- [ ] The code has been validated to compile successfully by running `go vet ./...`.
- [ ] The code has been formatted properly using `go fmt ./...`.

---

2024-05-09 17:15 UTC, eyalbe4 requested changes

2024-05-09 17:15 UTC, eyalbe4 commented on artifactory/cli.go
> +const permCategory = "Permission Target"
Target --> Targets

2024-05-09 17:15 UTC, eyalbe4 commented on artifactory/cli.go
> +const filesCategory = "Files"
Files --> Files Management

2024-05-15 08:23 UTC, yahavi requested changes
Looks good.
Please consider updating https://github.com/jfrog/documentation accordingly.

2024-05-15 08:23 UTC, yahavi commented on artifactory/cli.go
> +const otherCategory = "Other"
```suggestion
const (
	filesCategory    = "Files Management"
	buildCategory    = "Build Info"
	repoCategory     = "Repository Management"
	replicCategory   = "Replication"
	permCategory     = "Permission Targets"
	userCategory     = "User Management"
	transferCategory = "Transfer Between Artifactory Instances"
	otherCategory    = "Other"
)
```

2024-05-15 12:13 UTC, merged