Enhance download functionality to support RBV2
jfrog/jfrog-cli pull request #2805
Opened 2024-12-26 13:22 UTC by oshratZairi

- [ ] All [tests](https://github.com/jfrog/jfrog-cli/CONTRIBUTING.md#tests) have passed. If this feature is not already covered by the tests, new tests have been added.
- [ ] The pull request is targeting the `dev` branch.
- [ ] The code has been validated to compile successfully by running `go vet ./...`.
- [ ] The code has been formatted properly using `go fmt ./...`.

---
Enhance download functionality to support RBV2

2024-12-31 15:16 UTC, EyalDelarea requested changes

2024-12-31 15:16 UTC, EyalDelarea commented on go.mod
> +replace github.com/jfrog/jfrog-cli-core/v2 => ../jfrog-cli-core
Notice to change replaces before pushing :)

2025-01-06 07:24 UTC, oshratZairi commented on artifactory/cli.go
> +	//if the command contains --bundle and the bundle found in rbv2, we will download from rbv2
the logic is:
if we have the same rb-name in both rbv1 and rbv2 - we will take rbv2.
if the cmd dose not contain --bundle ,  it will remain as it is. 
moved the logic.

2025-01-09 15:13 UTC, EyalDelarea requested changes

2025-01-09 15:13 UTC, EyalDelarea commented on artifactory/cli.go
> +		Pattern(source).
Can we put all the source logic inside a function that will also explain why it should be different?

Something like this:
```go
func getSourcePattern(c *cli.Context) (string, error) {
	if c.IsSet("bundle") {
		isRbv2, err := checkRbExistenceInV2(c)
		if err != nil {
			log.Debug("Error occurred while checking if the bundle exists in rbv2:", err.Error())
		} else if isRbv2 {
			return buildSourceForRbv2(c)
		}
	}
	return strings.TrimPrefix(c.Args().Get(0), "/"), nil
}
```

then the line will look like this:

```go
return spec.NewBuilder().
		Pattern(getSourcePattern(c)).

2025-01-09 15:26 UTC, EyalDelarea commented
@oshratZairi looks good!

Just to extract the last function and fix the static check and we are good to go 👍

2025-01-12 15:12 UTC, EyalDelarea commented on artifactory/cli.go
> +
this could also move inside the `getSourcePattern` function

2025-01-14 12:13 UTC, EyalDelarea approved these changes

2025-01-14 12:13 UTC, merged