New general progress indication bar
jfrog/jfrog-cli pull request #914
Opened 2020-12-01 13:44 UTC by talarian1

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2020-12-02 11:43 UTC, RobiNino requested changes
Looks great!

2020-12-02 11:43 UTC, RobiNino commented on utils/progressbar/progressbar.go
>  	return spinnerFramesArray
The white color in this function should be changed to green to match the change in the reader progress bar

2020-12-10 15:12 UTC, eyalbe4 requested changes

2020-12-10 15:12 UTC, eyalbe4 commented on utils/progressbar/readerprogressbar.go
> +// Uses to updated the progress bar progress.
Uses to updated... --> Used to update...

2020-12-10 15:12 UTC, eyalbe4 commented on utils/progressbar/readerprogressbar.go
> +// Abort aborts a progress indication. Called on both successful and unsuccessful operations
indication --> indicator

2020-12-13 12:59 UTC, merged