Rename go.mod file in testdata
jfrog/jfrog-cli pull request #916
Opened 2020-12-02 09:26 UTC by talarian1

It was found that the go.mod files in the testdata causes undesired behavior in some IDEs.
Those files have been renamed to "createGoProject_go.mod_suffix" and will be
renamed back to "go.mod" in each test (inside a temporary folder).

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2020-12-02 12:49 UTC, RobiNino approved these changes

2020-12-02 12:55 UTC, RobiNino requested changes

2020-12-02 12:55 UTC, RobiNino commented on go_test.go
> +	os.Rename(goModeOriginalPath, goModeTargetPath)
```suggestion
	assert.NoError(t, os.Rename(goModeOriginalPath, goModeTargetPath))
```

2020-12-08 13:26 UTC, eyalbe4 approved these changes

2020-12-09 10:36 UTC, merged