Support 'include-deps' and 'exclude-artifacts' flags for search-based commands
jfrog/jfrog-cli pull request #927
Opened 2020-12-14 17:29 UTC by barbelity

- [ ] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2020-12-14 19:57 UTC, eyalbe4 requested changes
Let's add tests for the two new flags.

2020-12-14 19:57 UTC, eyalbe4 commented on artifactory/cli.go
> +		ExcludeArtifacts(c.Bool("exclude-artifacts")).
exclude-artifacts --> deps-only

2020-12-15 00:22 UTC, barbelity commented
We discussed about changing the 'exclude-artifacts' flag to 'deps-only', and decided to leave it as 'exclude-artifacts'.
Therefore, I am marking as 'resolved' all the comments requesting this change.

2020-12-15 11:58 UTC, eyalbe4 approved these changes

2020-12-15 12:55 UTC, merged