ant pattern
jfrog/jfrog-cli pull request #965
Opened 2021-01-31 17:24 UTC by gailazar300

- [X] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [X] This pull request is on the dev branch.
- [X] I used gofmt for formatting the code before submitting the pull request.
-----

2021-02-02 12:22 UTC, gailazar300 commented
I have read the CLA Document and I hereby sign the CLA

2021-02-05 16:36 UTC, eyalbe4 requested changes

2021-02-05 16:36 UTC, eyalbe4 commented on artifactory/cli.go
> +	if c.IsSet("regexp") && c.IsSet("ant") {
This check should be added into the ```spec.ValidateSpec``` function, Notice that this function is called a few lines below. Letting this function handle the validation, takes care fo both the flags and the file-spec validation.
Something else to notice:
The following flag combinations are valid:
```
--ant --regexp=false
--ant=false --regexp
--ant=treu --regexp=fase
```
and so on.
The ```spec.ValidateSpec``` function takes care of all of that very easilly.

2021-02-05 16:36 UTC, eyalbe4 commented on utils/cliutils/commandsflags.go
> +	badAnt: cli.BoolFlag{
It looks like this flag hasn't been added to the ```BuildAddDependencies``` slice, which includes all the flags of the ```build-add-dependencies``` command.

2021-02-05 16:36 UTC, eyalbe4 commented on artifactory_test.go
> +//This test checks the case of using --ant and --regexp at the same time
//This --> // This
(Our conversion is to add one white-space after //).

2021-02-05 16:36 UTC, eyalbe4 commented on go.mod
> +replace github.com/jfrog/jfrog-client-go => ../jfrog-client-go
To be reverted before committing.

2021-02-05 16:36 UTC, eyalbe4 commented on go.mod
> +replace github.com/jfrog/jfrog-cli-core => ../jfrog-cli-core
To be reverted before committing.

2021-02-15 08:36 UTC, eyalbe4 approved these changes

2021-02-21 14:36 UTC, merged