Added cleanup of old tests users
jfrog/jfrog-cli pull request #969
Opened 2021-02-04 10:20 UTC by talarian1

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-02-08 09:50 UTC, yahavi approved these changes

2021-02-11 08:34 UTC, eyalbe4 requested changes

2021-02-11 08:34 UTC, eyalbe4 commented on artifactory_test.go
> +	tests.CleanUpOldItems(tests.GetAllUsersNames(), getUsers, execDeleteUser)
GetAllUsersNames() --> GetTestUsersNames()

2021-02-11 08:34 UTC, eyalbe4 commented on artifactory_test.go
> +func getUsers() (usersnames []string, err error) {
getUsers() --> getAllUsernames()

2021-02-11 08:34 UTC, eyalbe4 commented on go.mod
> +// replace github.com/jfrog/jfrog-cli-core => github.com/jfrog/jfrog-cli-core dev
I think this replace should uncommented before committing.

2021-02-11 16:59 UTC, merged