Config
jfrog/jfrog-cli pull request #973
Opened 2021-02-16 15:31 UTC by yahavi

- [ ] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-02-16 15:41 UTC, yahavi commented on go.mod
> +replace github.com/jfrog/jfrog-cli-core => github.com/yahavi/jfrog-cli-core v0.0.0-20210216151620-6fed15f7878b
Reminder to change:
```suggestion
replace github.com/jfrog/jfrog-cli-core => github.com/jfrog/jfrog-cli-core dev
```

2021-02-24 13:38 UTC, eyalbe4 requested changes

2021-02-24 13:38 UTC, eyalbe4 commented on utils/cliutils/utils.go
> +		"You can also configure these parameters later using the 'jfrog rt c' command.\n"+
'jfrog rt c' --> 'jfrog c'

2021-02-24 13:54 UTC, yahavi commented on config/cli.go
> +func ValidateServerId(serverId string) error {
This function is in use in `addOrEdit`

2021-02-24 14:30 UTC, merged