Upload archive
jfrog/jfrog-cli pull request #986
Opened 2021-03-02 13:18 UTC by asafgabai

- [x] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-03-02 13:22 UTC, asafgabai commented on go.mod
> +replace github.com/jfrog/jfrog-cli-core => github.com/asafgabai/jfrog-cli-core upload-archive
Reminder for myself to change it back to dev

2021-03-04 16:52 UTC, eyalbe4 requested changes

2021-03-04 16:52 UTC, eyalbe4 commented on artifactory/cli.go
> +		Symlinks(c.Bool("symlinks")).
Shouldn't we also have ```archive``` here now? Does ```archive``` work with file specs?

2021-03-04 16:52 UTC, eyalbe4 commented on utils/cliutils/commandsflags.go
> +		Usage: "[Optional] Set to \"zip\" to deploy to Artifactory in a ZIP archive.` `",
...to deploy to Artifactory in a ZIP archive. --> ...to deploy to the files to Artifactory in a ZIP archive.

2021-03-07 12:02 UTC, eyalbe4 approved these changes

2021-03-07 18:30 UTC, merged